import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './circle.css'


// import Navbar from "@/components/navbar";
import Footer from '@/components/footer';
import AuthProvider from '@/providers/AuthProvider';

import toast, { Toaster } from 'react-hot-toast';

// import Head from 'next/head';
import MouseCircles from '@/app/mouseCircles';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div>
            {children}
            
            <Toaster position="bottom-center"/>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            <div className="circle hidden md:block"></div>
            
            <MouseCircles />
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
